import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { GetData } from "../components/getData";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [location, setLocation] = useState([]);
  const [data, setData] = useState(null);

  useEffect(() => {
    const getLocation = async () => {
      await navigator.geolocation.getCurrentPosition(
        (position) => {
          if (location.length == 0)
            setLocation([position.coords.latitude, position.coords.longitude]);
        },
        (err) => console.log(err)
      );
    };
    const getData = async () => {
      await getLocation();
      if (location.length > 0) {
        const datas = await GetData(location[0], location[1]);
        console.log(datas);
        return datas;
      }
    };
    getData();
    console.log(location);
  }, [location]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
